name: CD

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  workflow:
    name: Build and publish

    strategy:
      matrix:
        node: [18, 19]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    if: ${{ github.event.pull_request.merged }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/
          scope: "@inolib"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
