name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  continuous_integration:
    name: Lint, test, and build

    strategy:
      matrix:
        node: [18, 19]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run ci:lint

      - name: Test
        run: pnpm run ci:test

      - name: build
        run: pnpm run ci:build
